### PR TITLE
Racing line purge

### PR DESCRIPTION
**Pull request by jonathan-314**
added documentation
deleted lots of unused code
thanks

### CODE REVIEW

**Review by KevinPaulsen — DISMISSED** [review]

**Comment by KevinPaulsen** [comment]
Needs to be rebased. Should be super quick, your branch looks good.

**Comment by jonathan-314** [comment]
How do I do the rebase?

**Comment by KevinPaulsen** [comment]
1) go to terminal.
2) git fetch -a
3) git rebase origin/master
4) fix conflicts
5) git rebase --continue

If you need help, I can come over to you.

**Comment by KevinPaulsen** [comment]
I forgot step 6. after the continue type:
git push --force
(Make sure everything is working before you do this step)

**Comment by jonathan-314** [comment]
Ok I did all of those (including step 6)

**Comment by KevinPaulsen** [comment]
I kinda screwed you over... there was another commit to master (after you rebased) do it one more time.

**Comment by jonathan-314** [comment]
Don't worry there weren't any conflicts lol

**Review by KevinPaulsen — APPROVED** [review]

**Pull request merged**
